trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

# Define Variables
variables:
- name: DEV_ENVIRONMENT
  value: dev 
- name: QA_ENVIRONMENT
  value: qa

stages:
  - stage: terraformValidate
    jobs:
      - job: terraformValidate
        continueOnError: true
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'Published-artifacts'
            publishLocation: 'pipeline'
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'azuredevops_azurerm_svc'
            backendAzureRmResourceGroupName: 'terra'
            backendAzureRmStorageAccountName: 'terraformstatefileaccoun'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'aks-test.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'validate'
            